authgear/authgear-sdk-ios

- Sources/APIClient.swift
- Sources/AuthenticationSession.swift
- Sources/Authgear.swift
Format codes after upgrading swiftformat to 0.47.0
> Fix CI lint error

- Sources/APIClient.swift
- Sources/Authgear.swift
> Rename TokenResponse to OIDCTokenResponse

- Sources/Authgear.swift
> Rename AuthorizeResponse to AuthorizeResult

- Sources/Authgear.swift
> Add reason to session state did change handler

- Sources/Authgear.swift
> Separate calling handler and executing session action

- Sources/Authgear.swift
- iOS Example/iOS Example/AppDelegate.swift
- iOS Example/iOS Example/Base.lproj/Main.storyboard
- iOS Example/iOS Example/ViewController.swift
fix #24 
Use SFSafariViewController and handle OAuthRedirect manually instead
> Implement login flow without ASAuthenticationSession

- .github/workflows/test.yaml
> Install specific swiftformat version in CI

- Sources/Authgear.swift
> Fixed access token expiry check not having threshold

- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/AuthgearError.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
- example/ios_example/MainViewModel.swift
> Update for first-party clients

- Sources/Authgear.swift
- example/ios_example/MainViewModel.swift
> Handle connect with WeChat in setting page

- .swiftformat
- Authgear.xcodeproj/project.pbxproj
- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/Biometric.swift
- Sources/DeviceInfo.swift
- Sources/JWK.swift
- Sources/JWT.swift
- Sources/Storage.swift
- example/ios_example/App.swift
- example/ios_example/ContentView.swift
- example/ios_example/Info.plist
> Add biometric API

- Sources/Authgear.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
> Biometric authentication - part 2

- Sources/Authgear.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
> Remove isThirdParty

- Sources/Authgear.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
> Support transient session

- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/DeviceInfo.swift
> Include x_device_info

- Sources/APIClient.swift
- Sources/Authgear.swift
> Make SDK offline first

- Sources/Authgear.swift
> Rename `clearRefreshToken` to `clearSessionState`

- Sources/APIClient.swift
- Sources/AuthenticationSession.swift
- Sources/Authgear.swift
- Sources/AuthgearError.swift
- Sources/Biometric.swift
- Sources/JWK.swift
- Sources/JWT.swift
- Sources/Storage.swift
- example/ios_example/App.swift
> Unify all error variants into AuthgearError

- Sources/DeviceInfo.swift
> Collect CFBundleName

- Sources/Authgear.swift
- example/ios_example/App.swift
> Enumerate the possible values of prompt

- Sources/APIClient.swift
- Sources/AuthenticationSession.swift
- Sources/Authgear.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
refs #73 
TODO:
- Test x_suppress_idp_session_cookie parameter when server is ready
- When session type is `device`, should open webview to logout and revoke refresh token
> Support session type option in configure

- Sources/Authgear.swift
> Use ASWebAuthenticationSession to open URL

- Sources/Authgear.swift
- Sources/Storage.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
> Token storage

- README.md
Update Readme to add link and remove duplicated info
Resolve #82
> [Readme] Link to Authgear Doc and remove duplicated install info

- Sources/Authgear.swift
https://github.com/authgear/authgear-server/issues/2075
> Decode full UserInfo

- Sources/APIClient.swift
- Sources/AuthenticationSession.swift
- Sources/Authgear.swift
- Sources/AuthgearError.swift
- Sources/Biometric.swift
- Sources/JWK.swift
- Sources/Storage.swift
- example/ios_example/App.swift
> Support LAPolicy

- Sources/APIClient.swift
- Sources/Authgear.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
> Support ssoEnabled

- Sources/APIClient.swift
- Sources/Authgear.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
ref #87 
ref: https://www.swift.org/documentation/api-design-guidelines/#conventions
> Rename ssoEnabled to isSSOEnabled

- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/AuthgearError.swift
- example/ios_example/ContentView.swift
> Clear invalid session when calling require authenticated api

- Sources/Authgear.swift
ref authgear/authgear-server#2800
> Update authenticate to handle OAuth cancel error

- Sources/WebViewViewController.swift
> Set focus on webview on appear

- Sources/Authgear.swift
- Sources/AuthgearExperimental.swift
ref authgear/authgear-server#2899
Usage:
```swift
self.authgear.experimental.generateURL(redirectURI: "https://custom-ui.example.com/settings") { url in
print(url)
}
```
> Add experimental generateURL function

- Authgear.xcodeproj/project.pbxproj
- Sources/Latte+UniversalLink.swift
- Sources/Latte.swift
I changed the API a bit and added rewriteUniversalLinkOrigin to ease local development.
> Add LoginLinkHandler

- Sources/Latte+Flows.swift
- Sources/Latte+WKWebView.swift
- Sources/Latte.swift
refs authgear/2023C01-latte-customization#6
> Refactor LatteViewPageEvent to LatteAnalyticsEvent

- Sources/AuthgearError.swift
- Sources/Latte+UniversalLink.swift
ref https://github.com/authgear/2023C01-latte-customization/issues/138
> Change LatteLinkHandler to a enum

- Sources/Latte+Flows.swift
How to test:
In the view controller which trigger latte flows,
```swift
override func viewDidLoad() {
super.viewDidLoad()
self.navigationController!.interactivePopGestureRecognizer!.delegate = self
}
extension ViewController:UIGestureRecognizerDelegate {
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldBeRequiredToFailBy otherGestureRecognizer: UIGestureRecognizer) -> Bool {
return true
}
}
```
> [Latte] Handle swipe back in Latte view controller

- Sources/LatteError.swift
So that user can catch by error type
> [Make] Change LatteError to public

- Authgear.xcodeproj/project.pbxproj
- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/URL+origin.swift
ref [#248](https://github.com/authgear/authgear-sdk-js/issues/248)
> Generate urls by using origin in oidc config

- Sources/AuthgearError.swift
- Sources/app2app/App2App.swift
- Sources/app2app/App2AppAuthenticateRequest.swift
- Sources/app2app/App2AppAuthenticationOptions.swift
- example/ios_example/App.swift
- example/ios_example/ContentView.swift
https://github.com/authgear/authgear-sdk-ios/assets/34942210/40513619-d0c5-48c4-8f0c-e620b6063d56
> Add state to app2app

- Sources/Authgear.swift
- Sources/AuthgearExperimental.swift
> Improve compatibility between reauthentication and app2app

- Sources/AGWKWebViewController.swift
- Sources/WKWebViewUIImplementation.swift
ref https://github.com/authgear/authgear-server/issues/3864
> Open external browser for target="_blank" links in wkwebview ui implementation

- Sources/AGWKWebViewController.swift
- Sources/WKWebViewUIImplementation.swift
ref https://github.com/authgear/authgear-server/issues/3846
> Disable text selection in wkwebview

- Sources/Authgear.swift
ref https://github.com/authgear/authgear-server/issues/3924
> Decode roles

- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/AuthgearExperimental.swift
- example/ios_example/App.swift
- example/ios_example/ContentView.swift
> Close change password page on success

- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/AuthgearExperimental.swift
- example/ios_example/App.swift
- example/ios_example/ContentView.swift
> Support x_authentication_flow_group in authz request

- example/ios_example/App.swift
- example/ios_example/ContentView.swift
> List all user info attributes in example

- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/AuthgearError.swift
- Sources/AuthgearExperimental.swift
- Sources/Storage.swift
- Sources/app2app/App2App.swift
- example/ios_example/App.swift
- example/ios_example/AppDelegate.swift
- example/ios_example/ContentView.swift
ref DEV-1407
Test steps are same as https://github.com/authgear/authgear-sdk-js/pull/306
> Implement Pre-Authenticated URL

- Authgear.xcodeproj/project.pbxproj
- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/JWK+Thumbprint.swift
- Sources/JWK.swift
- Sources/JWT.swift
- Sources/Storage.swift
- Sources/app2app/App2App.swift
- Sources/dpop/DPoPProvider.swift
- Sources/dpop/DefaultDPoPProvider.swift
DEV-1446
requires https://github.com/authgear/authgear-sdk-ios/pull/173
> Implement DPoP

- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/AuthgearExperimental.swift
- example/ios_example/App.swift
- example/ios_example/ContentView.swift
> Support x_oauth_provider_alias

- Sources/Authgear.swift
- Sources/Latte+MigrateSession.swift
- Sources/Latte+Tokenize.swift
- Sources/Latte.swift
> Implement session migration method

- Sources/Latte+ProofOfPhoneNumberVerification.swift
> Implement proof of phone number verification

- .github/workflows/ci.yaml
- Makefile
> Use shared actions

- Sources/Latte+WKWebView.swift
> Handle external link in latte webview

- Sources/Latte+WKWebView.swift
- Sources/Latte.swift
> Add delegate callback for opening external URLs

- Sources/AGWKWebViewController.swift
- Sources/APIClient.swift
- Sources/Authgear.swift
- Sources/WKWebViewUIImplementation.swift
- example/ios_example/AppDelegate.swift
- flake.nix
> Support WeChat Login in WKWebViewUIImplementation

- Sources/Authgear.swift
- example/ios_example/App.swift
> Support LAPolicy.deviceOwnerAuthentication
